# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c678c2d7092ceb7370d09c6bd7ac0e44d5d56801e8b043a0e9dae1adcd240fb05b97d3636cafa061aa7c98c8835c3a4874632768b945e877fcd7b8e85db7e7c

test:
  secret_key_base: 4e4dd874a12a9602fb20f61df80244a88a11da358e4d58a2c03c5e33d1ce40442c70817e7b067e2db0784dfa894f90e22981cada5f6cc933108df2f021383ea4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
